### ISSUE TITLE
Determining a suitable timestep for RANS pimple case

### ISSUE THREAD

**Issue by tLashbrooke** [turbinesFoam/turbinesFoam#243]
Simulating a HATT and at a bit of a loss with determining suitable timesteps, do you have any hints? using dT = dX*Courant*Flowspeed gives values too high and going too small stretches out the runtime drastically... How do you hit the sweet spot? Will the varying of the TSR also require some ts adjustments?

**Comment by petebachant** [comment]
A good parameter to vary is time steps per rev.

If you take a look at this repo, you'll see I setup the `run.py` script to be able to run parameter sweeps of `dt` and `nx`, which produced:

![image](https://user-images.githubusercontent.com/4604869/36737947-4d86a964-1baa-11e8-8e2c-7060830f3a8f.png)

This was somewhat of an iterative process, since once a suitable `nx` was found, the `dt` sweep had to be rerun at that value, and vice versa.

**Comment by tLashbrooke** [comment]
Great! Thanks for your help Pete.
