### ISSUE TITLE
endEffects returns error in CW rotation

### ISSUE THREAD

**Issue by hcOnel** [turbinesFoam/turbinesFoam#247]
Upon running the provided axial flow tutorial with
axis (1 0 0);
I get the following error related to endEffects:

```
PIMPLE: iteration 1
#0  Foam::error::printStack(Foam::Ostream&) at ??:?
#1  Foam::sigFpe::sigHandler(int) at ??:?
#2  ? in "/lib/x86_64-linux-gnu/libc.so.6"
#3  acos in "/lib/x86_64-linux-gnu/libm.so.6"
#4  Foam::fv::axialFlowTurbineALSource::calcEndEffects() at ??:?
#5  Foam::fv::axialFlowTurbineALSource::addSup(Foam::fvMatrix<Foam::Vector<double> >&, int) at ??:?
#6  ? at ??:?
#7  ? at ??:?
#8  __libc_start_main in "/lib/x86_64-linux-gnu/libc.so.6"
#9  ? at ??:?
```

Active model is

```
        endEffects
        {
            active          on;
            endEffectsModel Glauert; // Glauert || Shen || liftingLine
            GlauertCoeffs
            {
                tipEffects  on;
                rootEffects on;
            }
        }
```
same as in the axialFlowTurbineAL tutorial. The code runs without error with endEffects active off.

**Comment by petebachant** [comment]
I think you're right! I'm going to test this out a bit.

**Comment by petebachant** [comment]
Implemented the limiting of the argument to `acos` on the `aftCW` branch if you'd like to test it out. So far it's failing tests due to low power coefficient, but it doesn't crash. I have a feeling there may be another geometry issue, e.g., with setting the blade twist.

**Comment by hcOnel** [comment]
Refreshed the git clone, Allwmake'd from scratch and re-run the case, and I'm still getting the same error. Still using the tutorial case axial flow.

**Comment by hcOnel** [comment]
Thanks for the info, deleted that pointless post of mine right after noticing that :)
Which part of the code do you suggest to focus on?

**Comment by hcOnel** [comment]
Crashing is no more, but now cp values are negative for the tutorial case.

**Comment by petebachant** [comment]
I have a feeling twist is being set incorrectly so the turbine is effectively a fan.

**Comment by hcOnel** [comment]
I couldn't notice a possible in `void Foam::fv::axialFlowTurbineALSource::createCoordinateSystem()`
Is this (https://github.com/turbinesFoam/turbinesFoam/issues/268#issuecomment-426271441) correction implemented?

**Comment by daa-mec** [comment]
Hi guys,

I have been reading the axisFlowTurbine source code in detail. And I have the impression that the twist angle is set correctly as a turbine. I will read this thread and see if I can help to spot any errors that might causing an issue. 

Until now.
The elements `chordDirection` is pitched at the end of `actuatorLineSource::createElements()`.
using the `actuatorElementSource::pitch(radians,chordFraction)`, where radians is set as the pitch angle in radians, and which it has been set to its negative value in `axialFlowTurbineALSource::createBlades()`. 

This rotation (pitching) is done along the `spanDirection` which is defined as discussed in #268, which makes perfect sense to me since in CCW turbine (Let's considered for simplicity one blade in vertical position), will have its `axis` pointing upstream, and thus the `spanDirection` will be the opposite vector to the `verticalDirection` (thus, pointing towards the root of the blade).

Having said that, and assuming that the RM perform the rotation following the right hand rule, when pitching the blades, a positive pitch angle will rotate the blade such that the leading edge moves backwards (downstream), and that the trailing edge moves forward (upstream). But since the pitch angle has been set to its negative value, it is doing the right thing, moving the leading edge forward, and the trailing edge backward. 

And finally, if the turbine CW, `axis` will point downstream, `spanDirection` will be as the `verticalDirection` (considering the blade at that position), and pitching the blades with the negative pitch angle, will do exactly what is expected again, move the leading edge forward and the trailing edge backward. 

I have also checked how the angle of attacks are determined and until now everything looks fine. But as I said, I will check this issue in more details to see if I can help.

**Comment by daa-mec** [comment]
I forgot to mention that the `chordNormal` is also set as it should be (with a component pointing downstream). I will continue the hunt for "the bug".

**Comment by petebachant** [comment]
Ah, so maybe it's just that the twist (pitch being a misnomer here; my fault) is opposite. W should probably add a test/tutorial case with the appropriate twist, but clockwise rotation--perhaps the NREL 5 MW.

**Comment by daa-mec** [comment]
Hi hcOnel, I think I do not understand the issue you are having.

Is it only that you get negative Cp values in the tutorial case?

**Comment by petebachant** [comment]
The issue is essentially passing an invalid value in to the `acos` function when computing the Glauert/Shen end effects models.

**Comment by daa-mec** [comment]
Hi hcOneI, as far as I can tell I could not find any bug. 

The only thing a did on comment #268, is that  at the moment using a `freeStreamVelocity_` not parallel to the `axis_` (whichever direction upstream or downstream), will lead to a `spanDirection_` different from a unitary vector. But apart from that I do not see any issues with changing the `axis_` direction, though I have not tested any CW cases yet. I will keep an eye on that. 

Now my question was about your comment:

> Crashing is no more, but now cp values are negative for the tutorial case.

I understood that after solving the issue with the `acos` function, you started to get negative cp values for the tutorial case.
