### ISSUE TITLE
[Question] double multiple streamtube model

### ISSUE THREAD

**Issue by ethren** [turbinesFoam/turbinesFoam#251]
Hello,
First off, sorry if this is a stupid question. is it possible to create Double multiple streamtube model solver in OpenFoam?

**Comment by petebachant** [comment]
No problem! With the actuator line method, since you solve for the flow with Navier--Stokes, there is no need to perform the streamtube calculations. The velocities and pressures are computed for each cell in the mesh.

**Comment by ethren** [comment]
Dear petebachant, if I understand well your answer then (correct me if I am mistaken): It is possible to implement double multiple streamtube model in OpenFOAM. 
Which model is more powerfull? the DMS (Double multiple streamtube) or Actuator line? can you please answer me in order to proceed to the next step because I have to decide which method to use.
Thank you very much

**Comment by petebachant** [comment]
I don't think there is any benefit to attempting to implement DMST in OpenFOAM, since the flow solution for DMST is very crude--a simple momentum balance with no evolution equation. Using Navier--Stokes with actuator lines is more powerful at resolving how the flow will behave since it includes nonlinear effects and turbulence can be modeled.
